foreground            #f9dcd7
background            #1e100d
selection_foreground  #670500
selection_background  #ffb4a7
url_color             #a7c8ff
cursor                #ffb4a7
cursor_text_color     #670500

color0   #1e100d
color1   #ffb4ab
color2   #ffb4a7
color3   #a7c8ff
color4   #ffb4a7
color5   #a7c8ff
color6   #0068c5
color7   #f9dcd7

color8   #ab8983
color9   #ffb4ab
color10  #ffb4a7
color11  #a7c8ff
color12  #ffb4a7
color13  #a7c8ff
color14  #0068c5
color15  #f9dcd7

tab_bar_background              #1e100d
tab_bar_margin_color            #1e100d
active_tab_foreground           #670500
active_tab_background           #ffb4a7
inactive_tab_foreground         #e4beb7
inactive_tab_background         #1e100d
