foreground            #e1e2eb
background            #11131a
selection_foreground  #002e69
selection_background  #adc6ff
url_color             #ffb780
cursor                #adc6ff
cursor_text_color     #002e69

color0   #11131a
color1   #ffb4ab
color2   #adc6ff
color3   #ffb780
color4   #adc6ff
color5   #ffb780
color6   #db760f
color7   #e1e2eb

color8   #8c909f
color9   #ffb4ab
color10  #adc6ff
color11  #ffb780
color12  #adc6ff
color13  #ffb780
color14  #db760f
color15  #e1e2eb

tab_bar_background              #11131a
tab_bar_margin_color            #11131a
active_tab_foreground           #002e69
active_tab_background           #adc6ff
inactive_tab_foreground         #c2c6d5
inactive_tab_background         #11131a
