foreground            #e8e0e5
background            #151216
selection_foreground  #442253
selection_background  #e4b7f3
url_color             #c1cd7d
cursor                #e4b7f3
cursor_text_color     #442253

color0   #151216
color1   #ffb4ab
color2   #e4b7f3
color3   #c1cd7d
color4   #e4b7f3
color5   #c1cd7d
color6   #505a16
color7   #e8e0e5

color8   #988e98
color9   #ffb4ab
color10  #e4b7f3
color11  #c1cd7d
color12  #e4b7f3
color13  #c1cd7d
color14  #505a16
color15  #e8e0e5

tab_bar_background              #151216
tab_bar_margin_color            #151216
active_tab_foreground           #442253
active_tab_background           #e4b7f3
inactive_tab_foreground         #cfc3ce
inactive_tab_background         #151216
