# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# Contributor: sadrach34 (mods and maintenance)
# Commands and Apps to be executed at launch

$scriptsDir = $HOME/.config/hypr/scripts
$UserScripts = $HOME/.config/hypr/UserScripts

$wallDIR=$HOME/Pictures/wallpapers
$lock = $scriptsDir/LockScreen.sh
# $SwwwRandom = $UserScripts/WallpaperAutoChange.sh
$livewallpaper="$HOME/Pictures/wallpapers/reze2-chainsaw-man.1920x1080.mp4"

# welcome window (one-time, after fresh install)
exec-once = $scriptsDir/welcome_launcher.sh
# default SDRX wallpapers (one-time, after fresh install)
exec-once = $scriptsDir/SetDefaultWallpapers.sh

# wallpaper stuff
exec-once = awww-daemon
exec-once = $scriptsDir/WallpaperAudioDaemon.sh
#exec-once = mpvpaper '*' -o "--load-scripts=no --no-audio --loop" $livewallpaper

# Apply random wallpaper on startup for all monitors
# exec-once = $UserScripts/WallpaperRandom.sh
exec-once = $UserScripts/MonitorWorkspaces.sh

# Startup
exec-once = pkill firefox # Clean any hanging Firefox processes from previous session
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = /usr/lib/xdg-desktop-portal-hyprland
# exec-once = $HOME/.config/hypr/UserConfigs/Startup_Apps.conf
# exec-once = /usr/lib/xdg-desktop-portal-gtk

# Polkit (Polkit Gnome / KDE)
exec-once = $scriptsDir/Polkit.sh

# starup apps
exec-once = handy --start-hidden
exec-once = nm-applet --indicator
exec-once = swaync
# exec-once = ags
#exec-once = blueman-applet
#exec-once = rog-control-center
exec-once = ~/.config/hypr/scripts/StartWaybar.sh
exec-once = $UserScripts/StartQuickshell.sh
exec-once = $scriptsDir/PowerProfileAuto.sh

#clipboard manager
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# Rainbow borders
exec-once = $UserScripts/RainbowBorders.sh

# Starting hypridle to start hyprlock
exec-once = hypridle
exec-once = $HOME/.config/hypr/UserScripts/PortalRestart.sh


# Here are list of features available but disabled by default
# exec-once = swww-daemon --format xrgb && swww img $HOME/Pictures/wallpapers/mecha-nostalgia.png  # persistent wallpaper

#gnome polkit for nixos
#exec-once = $scriptsDir/Polkit-NixOS.sh

# xdg-desktop-portal-hyprland (should be auto starting. However, you can force to start)
#exec-once = $scriptsDir/PortalHyprland.sh
