-- Generated by nwg-displays on 2026-05-29 at 18:51:09. Do not edit manually.

hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@74.97",
    position = "3000x160",
    scale = 1.0
})
hl.monitor({
    output = "DP-1",
    mode = "1920x1080@119.88",
    position = "1080x160",
    scale = 1.0
})
