#!/bin/bash
# Toggle between nwg-displays monitor profiles: normal <-> programar

ACTIVE_FILE="$HOME/.config/nwg-displays/active_profile.json"
MONITORS_CONF="$HOME/.config/hypr/monitors.conf"

CURRENT=$(jq -r '.active_profile' "$ACTIVE_FILE")

if [ "$CURRENT" = "normal" ]; then
    NEXT="programar"
    HDMI_TRANSFORM=1   # 90° vertical
else
    NEXT="normal"
    HDMI_TRANSFORM=0   # normal horizontal
fi

# Apply live via hyprctl (no Hyprland restart needed)
hyprctl keyword monitor "HDMI-A-1,1920x1080@74.97,3000x160,1"
hyprctl keyword monitor "HDMI-A-1,transform,$HDMI_TRANSFORM"

# Update monitors.conf so it persists on next Hyprland start
cat > "$MONITORS_CONF" << EOF
# Generated by ToggleMonitorProfile.sh on $(date '+%Y-%m-%d %H:%M:%S') — profile: $NEXT

monitor=DP-1,1920x1080@119.88,1080x160,1.0
monitor=HDMI-A-1,1920x1080@74.97,3000x160,1.0
monitor=HDMI-A-1,transform,$HDMI_TRANSFORM
EOF

# Update nwg-displays active profile
printf '{\n  "active_profile": "%s"\n}\n' "$NEXT" > "$ACTIVE_FILE"

# Restart waybar to adapt to new monitor layout
pkill waybar
sleep 0.3
"$HOME/.config/hypr/scripts/StartWaybar.sh" &

notify-send "Monitor Profile" "→ $NEXT" --icon=display --urgency=low
